scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:rose_cake"},"result":[{"item":"farmerscookbook:rose_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:berry_cake"},"result":[{"item":"farmerscookbook:berry_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:mohnkuchen"},"result":[{"item":"farmerscookbook:mohnkuchen_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:ice_cream_cake"},"result":[{"item":"farmerscookbook:ice_cream_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:glow_berry_cake"},"result":[{"item":"farmerscookbook:glow_berry_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:chorus_cake"},"result":[{"item":"farmerscookbook:chorus_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:chocolate_cake"},"result":[{"item":"farmerscookbook:chocolate_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:cheesecake"},"result":[{"item":"farmerscookbook:cheesecake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:carrot_cake"},"result":[{"item":"farmerscookbook:carrot_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:book_cake"},"result":[{"item":"farmerscookbook:book_cake_slice","count":7}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:brownie_tray"},"result":[{"item":"vanillacookbook:brownie","count":6}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scriptevent farmersdelight:cutting_board_recipe {"ingredients":{"item":"vanillacookbook:pancake_stack"},"result":[{"item":"vanillacookbook:pancake","count":5}],"tool":{"tag":"farmersdelight:is_knife"},"is_block_type":false,"sound":"use.wood"}
scoreboard objectives remove farmersdelight_farmerscookbook_cutting_board